version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.6
    container_name: homepage
    ports:
      - 80:3000
    volumes:
      - ./config:/app/config
      - /media/samba/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
        - CONTAINERS=1 # Allow access to viewing containers
        - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
        - 2375:2375
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
