---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Other:
    - Github:
        - abbr: GH
          href: https://github.com/
    - RegRU: 
        - abbr: RG
          href: https://www.reg.ru/
    - Shodan:
        - abbr: SHD
          href: https://www.shodan.io/
    - ЛК охраны труда:
        - abbr: ЛК ОТ
          href: https://lkot.mintrud.gov.ru/
    - Web Archive:
        - abbr: WA
          href: https://archive.org

- Shop:
    - Avito:
        - abbr: AV
          href: https://www.avito.ru/
    - PlatiMarket:
        - abbr: PM
          href: https://plati.market/
    - WMCentre:
        - abbr: WC
          href: https://wmcentre.net/
