---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Servers:

    - ProxMox:
        icon: proxmox.png
        href: https://192.168.1.153:8006
        widget:
          type: proxmox
          url: https://192.168.1.153:8006
          username: apihomepage@pam!apihomepage
          password: e0c0e36a-2fe5-4a6e-a710-b9ee1b15771c
          node: pvegorbunova # optional
    - ProxMox Mis:
        icon: proxmox.png
        href: http://10.204.18.249:8006
        ping: http://10.204.18.249
    - Kaspersky Security Center:
        icon: /icons/ksc.png
        href: https:/192.168.1.168:8080
        ping: https://192.168.1.168
    - WireGuard:
        icon: wireguard.png
        href: http://192.168.1.170:51821/
        ping: http://192.168.1.170
    - Portainer:
        icon: portainer.png
        href: https://192.168.1.172:9443
        ping: http://192.168.1.172
        widget:
          type: portainer
          url: https://192.168.1.172:9443
          env: 3
          key: ptr_n8vAdc3Et9YLyw7dFQW73l4/alW6udemG8uYsS6xX6k=
    - OMV:
        icon: openmediavault.png
        href: http://192.168.1.234
        ping: http://192.168.1.234
        widget:
          type: openmediavault
          url: http://192.168.1.234
          username: admin
          password: pr09ramm1$t
          method: services.getStatus # required
    - Pacs Admin:
        icon: /icons/pacs.png
        href: http://192.168.1.125/admin
        ping: http://192.168.1.125
    - IPMI PVE:
        icon: /icons/ipmi.png
        href: http://192.168.1.160/
        ping: http://192.168.1.160/

- Network:
    - Server Poliklinika:
        icon: /icons/qtech.png
        href: http://192.168.1.2
        ping: http://192.168.1.2
    - 1etag Poliklinika:
        icon: /icons/qtech.png
        href: http://192.168.1.3
        ping: http://192.168.1.3
    - 2etag Poliklinika:
        icon: /icons/qtech.png
        href: http://192.168.1.4
        ping: http://192.168.1.4
    - 2Etag Poliklinika:
        icon: tp-link.png
        href: http://192.168.1.5
        ping: http://192.168.1.5
    - 3etag Poliklinika:
        icon: /icons/qtech.png
        href: http://192.168.1.6
        ping: http://192.168.1.6
    - 3Etag Poliklinika:
        icon: tp-link.png
        href: http://192.168.1.7
        ping: http://192.168.1.7
    - 1 4etag Poliklinika:
        icon: /icons/qtech.png
        href: http://192.168.1.8
        ping: http://192.168.1.8
    - 2 4etag Poliklinika:
        icon: /icons/qtech.png
        href: http://192.168.1.9
        ping: http://192.168.1.9


- Web:
    - Mail:
        icon: synology-mail-plus.png
        href: https://e.mail.ru/inbox/      
    - Yandex:
        icon: yandex.png
        href: https://mail.yandex.ru/?uid=279120299#inbox
        ping: https://ya.ru
    - 2ip:
        icon: ipfs.png
        href: https://2ip.ru/
    - YouTube:
        icon: youtube.png
        href: https://www.youtube.com
    - Pacs:
        icon: /icons/pacs.png
        href: http://192.168.1.125
        ping: http://192.168.1.125
    - Laport:
        icon: /icons/laport.png
        href: http://10.216.1.245/laport/#/auth
        ping: http://10.216.1.245
    - Контур КЦР:
        icon: /icons/contur.ico
        href: https://kcr.kontur.ru
    - Контур личный кабинет:
        icon: /icons/contur.ico
        href: https://i.kontur-ca.ru
    - SDS support:
        icon: /icons/sds.ico
        href: https://support.sdsys.ru
    - ТФОМС:
        icon: /icons/tfoms.png
        href: https://zabtfoms.ru/register/findpolicy
    - MEDESK:
        icon: /icons/medesk.png
        href: https://legacy.medesk.ru/client/
        ping: https://legacy.medesk.ru
