---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank

- openmeteo:
    label: Chita
    latitude: 52.0317
    longitude: 113.501
    units: metric # or imperial
    cache: 5
